UPDATE amis_escalade.utilisateur SET nom = 'Florian', prenom = 'Firet', pseudo = 'admin', mail = 'admin@admin.fr', password = 'admin', isMembreOfficiel = 1 WHERE id = 11;
UPDATE amis_escalade.utilisateur SET nom = 'Corentin ', prenom = 'Coret', pseudo = 'users', mail = 'users@users.fr', password = 'users', isMembreOfficiel = 0 WHERE id = 12;
UPDATE amis_escalade.utilisateur SET nom = 'Bernard', prenom = 'Boulet', pseudo = 'users', mail = 'bernard@users.fr', password = 'bernard', isMembreOfficiel = 0 WHERE id = 13;

UPDATE amis_escalade.site SET nom = 'Ablon', departement = 'Haute-Savoie', pays = 'France', cotation_min = '4b', cotation_max = '8b', description = 'Situé en Haut-Savoie, ce site contient des vois avec une cotation allant de 4b à 8b. Orientation Sud-Est, la grimpe y est agréable !', type = 'Falaise', id_utilisateur = 11, tague = 0 WHERE id = 1;
UPDATE amis_escalade.site SET nom = 'Aile-Froide', departement = 'Hautes-Alpes', pays = 'France', cotation_min = '3a', cotation_max = '8a', description = 'Situé dans les Hautes-Alpes, ce site est parfait pour des sorties sprotive en famille !', type = 'Falaise', id_utilisateur = 11, tague = 0 WHERE id = 2;
UPDATE amis_escalade.site SET nom = 'Balme de Yenne', departement = 'Savoie', pays = 'France', cotation_min = '6b', cotation_max = '9a', description = 'Proche d''une rivère, le cadre y est magnifique.Les spots sont magnifique !', type = 'Falaise', id_utilisateur = 11, tague = 0 WHERE id = 3;
UPDATE amis_escalade.site SET nom = 'Salle de grimpe (Paris)', departement = 'Ile-de-France', pays = 'France', cotation_min = '4a', cotation_max = '6a', description = 'Mise en place dans une nouvelle salle, ce bloc est parfait pour les débutants.', type = 'Bloc', id_utilisateur = 12, tague = 0 WHERE id = 4;
UPDATE amis_escalade.site SET nom = 'Buoux ', departement = 'Vaucluse ', pays = 'France', cotation_min = '4b', cotation_max = '8c', description = 'Enormément de voies pour un max de fun !!', type = 'Falaise', id_utilisateur = 11, tague = 0 WHERE id = 5;
UPDATE amis_escalade.site SET nom = 'Salle Louis de Funès (Bordeaux)', departement = 'Gironde', pays = 'France', cotation_min = '3a', cotation_max = '6b', description = 'Superbe salle !', type = 'Bloc', id_utilisateur = 12, tague = 0 WHERE id = 6;

UPDATE amis_escalade.secteur SET nom = 'Ablon Sud ', description = 'Jolie secteur dans le sud d''Ablon', id_site = 1, id_utilisateur = 11 WHERE id = 12;
UPDATE amis_escalade.secteur SET nom = 'Ablon Nord ', description = 'Petit secteur au Nord d''Ablon', id_site = 1, id_utilisateur = 11 WHERE id = 13;
UPDATE amis_escalade.secteur SET nom = 'Aile-droite', description = 'Enorme possibilité de grimpe !', id_site = 2, id_utilisateur = 11 WHERE id = 14;
UPDATE amis_escalade.secteur SET nom = 'Aile-gauche', description = 'Secteur sympa.', id_site = 2, id_utilisateur = 11 WHERE id = 15;
UPDATE amis_escalade.secteur SET nom = 'Balme Ouest', description = 'Superbe endroit, à faire en famille ', id_site = 3, id_utilisateur = 11 WHERE id = 16;
UPDATE amis_escalade.secteur SET nom = 'Balme Est ', description = 'Petit secteur mais avec beaucoup de spot difficile', id_site = 3, id_utilisateur = 11 WHERE id = 17;
UPDATE amis_escalade.secteur SET nom = 'Salle A ', description = 'Pour grimpeur expérimentés', id_site = 4, id_utilisateur = 12 WHERE id = 18;
UPDATE amis_escalade.secteur SET nom = 'Salle B', description = 'Pour grimpeur amateur', id_site = 4, id_utilisateur = 12 WHERE id = 19;
UPDATE amis_escalade.secteur SET nom = 'Buoux ', description = 'Parfait pour passer une belle journée de grimpe', id_site = 5, id_utilisateur = 11 WHERE id = 20;
UPDATE amis_escalade.secteur SET nom = 'Salle de grimpe ', description = 'Pour tout niveaux.', id_site = 6, id_utilisateur = 12 WHERE id = 21;

UPDATE amis_escalade.voie SET nom = 'Ablon Sud 1 ', taille = 400, id_secteur = 12, id_utilisateur = 11 WHERE id = 7;
UPDATE amis_escalade.voie SET nom = 'Ablon Sud 2', taille = 200, id_secteur = 12, id_utilisateur = 11 WHERE id = 8;
UPDATE amis_escalade.voie SET nom = 'Ablon Nord 1', taille = 350, id_secteur = 13, id_utilisateur = 11 WHERE id = 9;
UPDATE amis_escalade.voie SET nom = 'Ablon Nord 2', taille = 400, id_secteur = 13, id_utilisateur = 11 WHERE id = 10;
UPDATE amis_escalade.voie SET nom = 'Voie des gagnants', taille = 500, id_secteur = 14, id_utilisateur = 11 WHERE id = 11;
UPDATE amis_escalade.voie SET nom = 'Voie des petits ', taille = 100, id_secteur = 14, id_utilisateur = 11 WHERE id = 12;
UPDATE amis_escalade.voie SET nom = 'Voie des moyens', taille = 200, id_secteur = 14, id_utilisateur = 11 WHERE id = 13;
UPDATE amis_escalade.voie SET nom = 'Voie des monstres', taille = 600, id_secteur = 15, id_utilisateur = 11 WHERE id = 14;
UPDATE amis_escalade.voie SET nom = 'Balme d''or', taille = 450, id_secteur = 16, id_utilisateur = 11 WHERE id = 15;
UPDATE amis_escalade.voie SET nom = 'Balme d''argent', taille = 350, id_secteur = 16, id_utilisateur = 11 WHERE id = 16;
UPDATE amis_escalade.voie SET nom = 'Balme de bronze ', taille = 200, id_secteur = 17, id_utilisateur = 11 WHERE id = 17;
UPDATE amis_escalade.voie SET nom = 'Balme en toc', taille = 100, id_secteur = 17, id_utilisateur = 11 WHERE id = 18;
UPDATE amis_escalade.voie SET nom = 'Voie de Napoléon', taille = 20, id_secteur = 18, id_utilisateur = 12 WHERE id = 19;
UPDATE amis_escalade.voie SET nom = 'Voie de Chirac', taille = 40, id_secteur = 19, id_utilisateur = 12 WHERE id = 20;
UPDATE amis_escalade.voie SET nom = 'Petite voie de la raison', taille = 60, id_secteur = 20, id_utilisateur = 11 WHERE id = 21;
UPDATE amis_escalade.voie SET nom = 'Voie Afflelou', taille = 50, id_secteur = 21, id_utilisateur = 12 WHERE id = 22;

UPDATE amis_escalade.longueur SET id_voie = 7, nbre_points = 5, taille = 50, cotation = '4b', id_utilisateur = 11 WHERE id = 9;
UPDATE amis_escalade.longueur SET id_voie = 7, nbre_points = 10, taille = 100, cotation = '8b', id_utilisateur = 11 WHERE id = 10;
UPDATE amis_escalade.longueur SET id_voie = 8, nbre_points = 7, taille = 70, cotation = '6a', id_utilisateur = 11 WHERE id = 11;
UPDATE amis_escalade.longueur SET id_voie = 8, nbre_points = 6, taille = 60, cotation = '4c', id_utilisateur = 11 WHERE id = 12;
UPDATE amis_escalade.longueur SET id_voie = 8, nbre_points = 5, taille = 50, cotation = '5c', id_utilisateur = 11 WHERE id = 13;
UPDATE amis_escalade.longueur SET id_voie = 9, nbre_points = 4, taille = 40, cotation = '6a', id_utilisateur = 11 WHERE id = 14;
UPDATE amis_escalade.longueur SET id_voie = 9, nbre_points = 7, taille = 70, cotation = '6c', id_utilisateur = 11 WHERE id = 15;
UPDATE amis_escalade.longueur SET id_voie = 9, nbre_points = 8, taille = 80, cotation = '7c', id_utilisateur = 11 WHERE id = 16;
UPDATE amis_escalade.longueur SET id_voie = 10, nbre_points = 10, taille = 100, cotation = '8a', id_utilisateur = 11 WHERE id = 17;
UPDATE amis_escalade.longueur SET id_voie = 10, nbre_points = 8, taille = 80, cotation = '7a', id_utilisateur = 11 WHERE id = 18;
UPDATE amis_escalade.longueur SET id_voie = 11, nbre_points = 2, taille = 20, cotation = '3a', id_utilisateur = 11 WHERE id = 19;
UPDATE amis_escalade.longueur SET id_voie = 11, nbre_points = 4, taille = 40, cotation = '6a', id_utilisateur = 11 WHERE id = 20;
UPDATE amis_escalade.longueur SET id_voie = 12, nbre_points = 7, taille = 70, cotation = '7a', id_utilisateur = 11 WHERE id = 21;
UPDATE amis_escalade.longueur SET id_voie = 12, nbre_points = 8, taille = 80, cotation = '8a', id_utilisateur = 11 WHERE id = 22;
UPDATE amis_escalade.longueur SET id_voie = 13, nbre_points = 4, taille = 40, cotation = '5a', id_utilisateur = 11 WHERE id = 23;
UPDATE amis_escalade.longueur SET id_voie = 13, nbre_points = 4, taille = 40, cotation = '4c', id_utilisateur = 11 WHERE id = 24;
UPDATE amis_escalade.longueur SET id_voie = 14, nbre_points = 3, taille = 35, cotation = '5c', id_utilisateur = 11 WHERE id = 25;
UPDATE amis_escalade.longueur SET id_voie = 14, nbre_points = 4, taille = 40, cotation = '5b', id_utilisateur = 11 WHERE id = 26;
UPDATE amis_escalade.longueur SET id_voie = 14, nbre_points = 4, taille = 45, cotation = '4b', id_utilisateur = 11 WHERE id = 27;
UPDATE amis_escalade.longueur SET id_voie = 15, nbre_points = 15, taille = 150, cotation = '9a', id_utilisateur = 11 WHERE id = 28;
UPDATE amis_escalade.longueur SET id_voie = 15, nbre_points = 10, taille = 100, cotation = '9a', id_utilisateur = 11 WHERE id = 29;
UPDATE amis_escalade.longueur SET id_voie = 16, nbre_points = 7, taille = 70, cotation = '6c', id_utilisateur = 11 WHERE id = 30;
UPDATE amis_escalade.longueur SET id_voie = 16, nbre_points = 8, taille = 80, cotation = '8c', id_utilisateur = 11 WHERE id = 31;
UPDATE amis_escalade.longueur SET id_voie = 17, nbre_points = 8, taille = 80, cotation = '8a', id_utilisateur = 11 WHERE id = 32;
UPDATE amis_escalade.longueur SET id_voie = 17, nbre_points = 8, taille = 80, cotation = '8b', id_utilisateur = 11 WHERE id = 33;
UPDATE amis_escalade.longueur SET id_voie = 18, nbre_points = 6, taille = 60, cotation = '6a', id_utilisateur = 11 WHERE id = 34;
UPDATE amis_escalade.longueur SET id_voie = 18, nbre_points = 6, taille = 60, cotation = '6a', id_utilisateur = 11 WHERE id = 35;
UPDATE amis_escalade.longueur SET id_voie = 18, nbre_points = 6, taille = 60, cotation = '6b', id_utilisateur = 11 WHERE id = 36;
UPDATE amis_escalade.longueur SET id_voie = 19, nbre_points = 2, taille = 20, cotation = '4a', id_utilisateur = 12 WHERE id = 37;
UPDATE amis_escalade.longueur SET id_voie = 19, nbre_points = 2, taille = 20, cotation = '5a', id_utilisateur = 12 WHERE id = 38;
UPDATE amis_escalade.longueur SET id_voie = 20, nbre_points = 2, taille = 20, cotation = '6a', id_utilisateur = 12 WHERE id = 39;
UPDATE amis_escalade.longueur SET id_voie = 21, nbre_points = 5, taille = 50, cotation = '4b', id_utilisateur = 11 WHERE id = 40;
UPDATE amis_escalade.longueur SET id_voie = 21, nbre_points = 8, taille = 80, cotation = '8c', id_utilisateur = 11 WHERE id = 41;
UPDATE amis_escalade.longueur SET id_voie = 22, nbre_points = 2, taille = 20, cotation = '3a', id_utilisateur = 12 WHERE id = 42;
UPDATE amis_escalade.longueur SET id_voie = 22, nbre_points = 2, taille = 20, cotation = '5a', id_utilisateur = 12 WHERE id = 43;
UPDATE amis_escalade.longueur SET id_voie = 22, nbre_points = 3, taille = 4, cotation = '6b', id_utilisateur = null WHERE id = 44;

UPDATE amis_escalade.topos SET nom = 'Topo d''Ablon', description = 'Superbe topo sur le site d''Ablon.', lieu = 'Ablon', is_reserve = 0, date = '2018-08-01', id_utilisateur = 11 WHERE id = 7;
UPDATE amis_escalade.topos SET nom = 'Topo d''Aile-Froide', description = 'Topo complet d''Aile-Froide.', lieu = 'Aile-Froide', is_reserve = 0, date = '2016-02-17', id_utilisateur = 11 WHERE id = 8;
UPDATE amis_escalade.topos SET nom = 'Topo de Balme de Yenne', description = 'Topo de Balme de Yenne. ', lieu = 'Balme de Yenne', is_reserve = 0, date = '2016-09-14', id_utilisateur = 11 WHERE id = 9;
UPDATE amis_escalade.topos SET nom = 'Topo de Paris Salle de grimpe', description = 'Topo sur la salle à Paris, salle de grimpe.', lieu = 'Paris', is_reserve = 0, date = '2020-01-18', id_utilisateur = 12 WHERE id = 10;
UPDATE amis_escalade.topos SET nom = 'Topo de Buoux', description = 'Topo sur le site de Buoux, très bien fait.', lieu = 'Buoux', is_reserve = 0, date = '2015-11-11', id_utilisateur = 13 WHERE id = 11;
UPDATE amis_escalade.topos SET nom = 'Topo de Bordeaux Salle de Louis de Funès', description = 'Topo sur la salle de Louis de Funès, situé à Bordeaux.', lieu = 'Bordeaux', is_reserve = 0, date = '2019-08-07', id_utilisateur = 12 WHERE id = 12;